#!/bin/bash
#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=setup-models
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=job_outputs/models_%A.out

# Step 1: Load required modules
module purge
module load 2023
module load Anaconda3/2023.07-2
eval "$(/sw/arch/RHEL8/EB_production/2023/software/Anaconda3/2023.07-2/bin/conda shell.bash hook)"
conda activate opensora

cd $HOME/Open-Sora

export HF_HUB_DOWNLOAD_TIMEOUT=300

pip install "huggingface_hub[cli]"
huggingface-cli download hpcai-tech/Open-Sora-v2 --local-dir ./ckpts

# pip install modelscope
# modelscope download hpcai-tech/Open-Sora-v2 --local_dir ./ckpts