#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=sora_run
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=/home/scur0552/personalization_iwo/outputs/clip_personalized/sora_iwo_%A.out

# Step 1: Load Anaconda
module purge
module load 2023
module load Anaconda3/2023.07-2
module load CUDA/12.1.1  # <-- this is the fix that adds missing cuda_runtime_api.h


eval "$(/sw/arch/RHEL8/EB_production/2023/software/Anaconda3/2023.07-2/bin/conda shell.bash hook)" # doesnt work without it

conda activate opensora

pip install scikit-learn

#pip install git+https://github.com/hpcaitech/TensorNVMe.git

cd $HOME/Open-Sora
python ~/personalization_iwo/generate_combined.py